# Generated by Django 3.2.3 on 2021-05-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listingid', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('bid_amount', models.PositiveIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('listingid', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=250)),
                ('owner', models.CharField(max_length=64)),
                ('starting_price', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('ENTERTAINMENT', 'Entertainment'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('GENERAL', 'General'), ('HOME', 'Home'), ('TOYS', 'Toys')], default='GENERAL', max_length=13)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('listingid', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('bid_amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
