# Generated by Django 3.2.3 on 2021-05-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('listingid', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('bid_amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='timestamp',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='winner',
        ),
    ]
