# Generated by Django 3.2.3 on 2021-05-31 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_starting_price_listings_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
